<a href="https://colab.research.google.com/github/Adhira-Deogade/pytorch-learnings/blob/main/linear_regression_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [12]:
in1 = np.arange(1.0, 11.0)
print(in1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
X = torch.from_numpy(in1)
print(X)
print(X.shape)
print(X.dtype)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
torch.Size([10])
torch.float64


In [14]:
out1 = np.arange(2.0, 21.0, step=2)
print(out1)
Y = torch.from_numpy(out1)
print(Y)
print(Y.shape)
print(Y.dtype)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], dtype=torch.float64)
torch.Size([10])
torch.float64


In [35]:
w = torch.tensor(1, dtype=torch.float32, requires_grad=True)
print(w)

tensor(1., requires_grad=True)


In [36]:
print(w.grad)

None


In [37]:
# Model output
def forward(x):
  return w * x

# loss = Mean Squared Error (MSE)
def loss(y, y_pred):
  return ((y_pred-y)**2).mean()

# Evaluation
X_test = [0.5, 32, 200]


In [38]:
print(f"Prediction before training: f(X_test):")
for item in X_test:
  y_pred = forward(item).item()
  print(y_pred)

Prediction before training: f(X_test):
0.5
32.0
200.0


In [55]:
# Training
w = torch.tensor(0, dtype=torch.float32, requires_grad=True)
print(w)
learning_rate = 0.01
epochs = 20

for epoch in range(epochs):
  # print(f"epoch = {epoch}")
  y_pred = forward(X)
  # print(f"y, y_pred = {Y}, {y_pred}")

  l = loss(Y, y_pred)
  # print(f"loss = {l}")

  # Calculate gradient = backward pass
  l.backward()
  # print(f"backward = {l}")

  # Update weights
  with torch.no_grad():
    w -= (learning_rate * w.grad)
    # print(f"w = {w}")
    # print(f"w.dtype = {w.dtype}")
    # print(f"w.grad = {w.grad}")

  # Zero the gradients after updating
  w.grad.zero_()

  # if (epoch+1) % 10 == 0:
  print(f"epoch ({epoch+1}); w ({w.item()}); loss ({l.item()})")
  # break




tensor(0., requires_grad=True)
epoch (1); w (1.5399999618530273); loss (154.0)
epoch (2); w (1.8941999673843384); loss (8.146601351165828)
epoch (3); w (1.9756660461425781); loss (0.4309554057067899)
epoch (4); w (1.9944032430648804); loss (0.022797440447902773)
epoch (5); w (1.9987127780914307); loss (0.001205961995346172)
epoch (6); w (1.9997038841247559); loss (6.379219931318403e-05)
epoch (7); w (1.9999319314956665); loss (3.375857545506733e-06)
epoch (8); w (1.9999843835830688); loss (1.783828693646683e-07)
epoch (9); w (1.9999964237213135); loss (9.389090394051891e-09)
epoch (10); w (1.9999991655349731); loss (4.924061158817494e-10)
epoch (11); w (1.999999761581421); loss (2.680877742022858e-11)
epoch (12); w (2.0); loss (2.1884716261411086e-12)
epoch (13); w (2.0); loss (0.0)
epoch (14); w (2.0); loss (0.0)
epoch (15); w (2.0); loss (0.0)
epoch (16); w (2.0); loss (0.0)
epoch (17); w (2.0); loss (0.0)
epoch (18); w (2.0); loss (0.0)
epoch (19); w (2.0); loss (0.0)
epoch (20); w 

In [56]:
print(f"Prediction after training: f(X_test):")
for item in X_test:
  y_pred = forward(item).item()
  print(y_pred)

Prediction after training: f(X_test):
1.0
64.0
400.0
