<a href="https://colab.research.google.com/github/Adhira-Deogade/pytorch-learnings/blob/main/model_loss_optimizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Use built-in functions for forward, loss and updating weights

In [3]:
# A typical pytorch pipeline looks like this -
# 1. Design - inputs, outputs, forward pass through layers
# 2. Construct - loss and optimizer
# 3. Training loop
#   - forward pass - compute prediction and loss
#   - compute gradient
#   - update weights

In [4]:
# Linear regression example in the pytorch way

In [5]:
import torch
import torch.nn as nn

In [6]:
# Linear regression
# f(x) =  wx
# here: f(x) = 2x

In [7]:
import numpy as np

In [18]:
in1 = np.arange(1,10, dtype=np.float32)
print(in1)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
in1_torch = torch.from_numpy(in1)
print(in1_torch)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [20]:
in1_torch.shape

torch.Size([9])

In [21]:
# Now, I want a 9 by 1 tensor, how will I achieve that?
# Let's try reshaping

In [34]:
X = in1_torch.view(9,1)

In [35]:
print(X.shape)

torch.Size([9, 1])


In [36]:
print(X)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [37]:
Y = 2 * X # This creates a copy of tensor, nothing changes in memory

In [38]:
print(Y)

tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.],
        [14.],
        [16.],
        [18.]])


In [39]:
n_samples, n_features = X.shape
print(n_samples, n_features)

9 1


In [46]:
# Create a tensor for evaluation/ testing
in_test = np.arange(11,20, dtype=np.float32)
in_test_torch = torch.from_numpy(in_test)
X_test = in_test_torch.view(9,1)
# X_test = torch.tensor([5], dtype=torch.float32)

In [47]:
print(X_test)

tensor([[11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.]])


In [48]:
X.dtype

torch.float32

In [49]:
Y.dtype

torch.float32

In [52]:
# 1. Design model, the model has to implement forward pass
# We can use built-in model from pytorch
# model = nn.Linear(input_size, output_size)

In [68]:
class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
    # Define all the layers
    super(LinearRegression, self).__init__()
    # We are creating only 1 layer here
    self.lin = nn.Linear(input_dim, output_dim)

  def forward(self, x):
    # Get the input tensor
    # Apply all the layers
    return self.lin(x)

In [54]:
input_size, output_size = n_features, n_features

In [55]:
print(input_size, output_size)

1 1


In [69]:
linear_model = LinearRegression(input_dim=input_size, output_dim=output_size)

In [70]:
print(linear_model)

LinearRegression(
  (lin): Linear(in_features=1, out_features=1, bias=True)
)


In [71]:
print(f"Prediction before training: f({X_test}):")
print(linear_model(X_test))

Prediction before training: f(tensor([[11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.]])):
tensor([[4.3408],
        [4.7473],
        [5.1538],
        [5.5603],
        [5.9668],
        [6.3733],
        [6.7798],
        [7.1863],
        [7.5928]], grad_fn=<AddmmBackward0>)


In [72]:
# 2. Define loss and optimizer
learning_rate = 0.01
epochs = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(linear_model.parameters(), lr=learning_rate)

print(f"learning rate: {learning_rate}")
print(f"epochs: {epochs}")
print(f"loss: {loss}")
print(f"optimizer: {optimizer}")

learning rate: 0.01
epochs: 100
loss: MSELoss()
optimizer: SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [73]:
# 3. Training loop
for epoch in range(epochs):
  # Make a prediction
  y_pred = linear_model.forward(X)

  # Compute loss
  l = loss(Y, y_pred)

  # Compute gradient descent
  l.backward() # dl/dw

  # Update weights
  optimizer.step()

  # Zero the gradient for next iteration
  optimizer.zero_grad()

  if (epoch+1) % 10 == 0:
    weight, bias = linear_model.parameters()
    print(f"epoch({epoch+1}); loss({l}); weight({weight[0][0]}); bias({bias[0]})")


epoch(10); loss(0.002788752317428589); weight(1.9817426204681396); bias(0.11459372937679291)
epoch(20); loss(0.0025678868405520916); weight(1.982521414756775); bias(0.10997967422008514)
epoch(30); loss(0.0023649726063013077); weight(1.9832262992858887); bias(0.10554491728544235)
epoch(40); loss(0.002178063616156578); weight(1.9839025735855103); bias(0.10128893703222275)
epoch(50); loss(0.0020059836097061634); weight(1.9845516681671143); bias(0.09720462560653687)
epoch(60); loss(0.0018474470125511289); weight(1.9851746559143066); bias(0.093284972012043)
epoch(70); loss(0.0017014637123793364); weight(1.9857724905014038); bias(0.08952341973781586)
epoch(80); loss(0.0015670250868424773); weight(1.9863462448120117); bias(0.0859135165810585)
epoch(90); loss(0.0014431994641199708); weight(1.9868967533111572); bias(0.08244915306568146)
epoch(100); loss(0.0013291504001244903); weight(1.9874250888824463); bias(0.07912448793649673)


In [74]:
print(f"Prediction after training: f({X_test}): {linear_model(X_test)}")

Prediction after training: f(tensor([[11.],
        [12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.]])): tensor([[21.9408],
        [23.9282],
        [25.9157],
        [27.9031],
        [29.8905],
        [31.8779],
        [33.8654],
        [35.8528],
        [37.8402]], grad_fn=<AddmmBackward0>)


In [86]:
print(f"Prediction after training: f(100): {linear_model(torch.tensor([100.0]))}")

Prediction after training: f(100): tensor([198.8216], grad_fn=<ViewBackward0>)


In [81]:
print(X)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
