<a href="https://colab.research.google.com/github/Adhira-Deogade/pytorch-learnings/blob/main/softmax_and_cross_entropy_loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# Rerence video - https://youtu.be/7q7E91pHoW4?si=SIdA4clxooyq9XVy

In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def softmax(x):
  return (np.exp(x))/(np.sum(np.exp(x), axis=0))

In [8]:
np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.float32, axis=0)

np.float32(2.9)

In [10]:
# np.sum([0.5, 0.7, 0.2, 1.5], dtype=np.float32, axis=1) # This gives error

In [11]:
x = np.array([0.5, 0.7, 0.2, 1.5])
print(x)

[0.5 0.7 0.2 1.5]


In [14]:
y = (softmax(x))
print(x)
print(y)
print(np.sum(y))

[0.5 0.7 0.2 1.5]
[0.17604075 0.21501666 0.1304142  0.47852838]
1.0


In [15]:
# Highest probability value for highest value in output

<ipython-input-16-4c26ec200d28>:1: RuntimeWarning: invalid value encountered in log
  np.log(-0.0022)


np.float64(nan)

In [21]:
# Example of target with class indices
print("Example of target with class indices")
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(f"input = {input}")
target = torch.empty(3, dtype=torch.long).random_(5)
print(f"target = {target}")
print(f"target.shape = {target.shape}")
output = loss(input, target)
print(f"output = {output}")
output.backward()
print(f"output = {output}")


Example of target with class indices
input = tensor([[-0.2823,  0.5743, -0.7504, -0.7256, -0.5473],
        [-0.0594,  1.0054, -0.3947, -1.1711,  1.0992],
        [-0.8645, -0.6240, -1.2024, -1.0309,  0.9463]], requires_grad=True)
target = tensor([3, 2, 0])
target.shape = torch.Size([3])
output = 2.285362958908081
output = 2.285362958908081


In [19]:
# Example of target with class probabilities
print("Example of target with class probabilities")
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(f"input = {input}")
target = torch.randn(3, 5).softmax(dim=1)
print(f"target = {target}")
output = loss(input, target)
print(f"output = {output}")
output.backward()
print(f"output = {output}")

Example of target with class probabilities
input = tensor([[-1.0758,  0.6150, -1.7041, -1.0720, -0.2187],
        [ 0.5714,  1.3511, -1.1054,  0.2001, -1.2003],
        [ 0.6462,  0.9317, -0.9245, -0.4187,  1.3223]], requires_grad=True)
target = tensor([[0.1593, 0.3300, 0.2603, 0.1380, 0.1124],
        [0.1647, 0.3770, 0.1023, 0.1425, 0.2134],
        [0.3219, 0.1392, 0.1268, 0.2825, 0.1297]])
output = 1.8480762243270874
output = 1.8480762243270874


In [22]:
def cross_entroy_loss(y, y_pred):
  return -(np.sum(y * np.log(y_pred)))

In [23]:
y = np.array([1, 0, 0])
y_pred_good = np.array([0.7, 0.2, 0.1])
y_pred_bad = np.array([0.1, 0.3, 0.6])
print(f"y = {y}")
print(f"y_pred_good = {y_pred_good}")
print(f"y_pred_bad = {y_pred_bad}")

y = [1 0 0]
y_pred_good = [0.7 0.2 0.1]
y_pred_bad = [0.1 0.3 0.6]


In [24]:
cel = cross_entroy_loss(y, y_pred_good)
print(f"cel = {cel}")

cel = 0.35667494393873245


In [25]:
cel_bad = cross_entroy_loss(y, y_pred_bad)
print(f"cel_bad = {cel_bad}")

cel_bad = 2.3025850929940455


In [26]:
# y must be one-hot encoded
# y = 0 -> y = [1, 0, 0]
# y = 1 -> y = [0, 1, 0]
# y = 2 -> y = [0, 0, 1]

In [27]:
# y_pred has probabilities

In [28]:
# Let's do this in pytorch

In [30]:
loss = nn.CrossEntropyLoss()
# nn.CrossEntropyLoss applies
# 1. nn.LogSoftMax
# 2. nn.NLLLoss (Negative Log likelihood loss)
# /content/Screen Shot 2025-05-27 at 10.23.11 AM.png