<a href="https://colab.research.google.com/github/Adhira-Deogade/pytorch-learnings/blob/main/pytorch_tutorial_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pytroch creash course - https://www.youtube.com/watch?v=OIenNRt2bjg

In [2]:
# Let's learn about tensors

In [3]:
# Pytorch is a tensor based operation. A tensor is a multi-dimensional matrix
# with elements of same datatype

In [1]:
import torch

In [5]:
x = torch.empty(1)
print(f"empty(1) tensor: {x}")

empty(1) tensor: tensor([6.3719e-17])


In [6]:
x = torch.empty(3)
print(f"empty(3) tensor: {x}")

empty(3) tensor: tensor([6.3720e-17, 4.5496e-41, 6.3720e-17])


In [7]:
x = torch.empty(2,4)
print(f"empty(2,4) tensor: {x}")
# 2 arrays of 4 elements
# A matrix of 2 rows, and 4 columns

empty(2,4) tensor: tensor([[6.3720e-17, 4.5496e-41, 6.3720e-17, 4.5496e-41],
        [4.4842e-44, 0.0000e+00, 1.7937e-43, 0.0000e+00]])


In [8]:
x = torch.empty(1,1)
print(f"empty(1,1) tensor: {x}")
# 1 array of an array with 1 element
# A matrix of 1 row, and 1 column

empty(1,1) tensor: tensor([[6.3720e-17]])


In [9]:
x = torch.empty(1,2)
print(f"empty(1,2) tensor: {x}")
# 1 array of an array with 2 elements
# A matrix of 1 row and 2 columns

empty(1,2) tensor: tensor([[2.7654e-32, 0.0000e+00]])


In [10]:
x = torch.rand(1,2)
print(f"rand(1,2) tensor: {x}")
# 1 array of an array with 2 elements
# A matrix of 1 row and 2 columns

rand(1,2) tensor: tensor([[0.1133, 0.5282]])


In [11]:
# I see the difference between empty and rand
# empty returns values which are almost zero, what computer returns
# rand returns actual values which are non-zero

In [12]:
x = torch.rand(2,5)
print(f"rand(2,5) tensor: {x}")
# 2 arrays of 5 elements each
# A matrix of 2 row and 5 columns

rand(2,5) tensor: tensor([[0.9152, 0.0891, 0.4106, 0.9683, 0.1103],
        [0.7569, 0.1688, 0.3705, 0.7396, 0.5240]])


In [13]:
# scalar = returns an array
# vector/ tensor = returns an array of array

In [14]:
x = torch.zeros(2,5)
print(f"zeros(2,5) tensor: {x}")
# 2 arrays of 5 elements each
# A matrix of 2 row and 5 columns

zeros(2,5) tensor: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [15]:
# Now I am getting an exact value of zero

In [16]:
x = torch.zeros(1)
print(f"zeros(1) tensor: {x}")
# an array of element

zeros(1) tensor: tensor([0.])


In [17]:
# We can create not just a matrix but a multi-dimensional matrix
x = torch.rand(1,1,1)
print(f"rand(1,1,1) tensor: {x}")
# An array of an array of an arrays of 1 element
# x, y and z

rand(1,1,1) tensor: tensor([[[0.6914]]])


In [18]:
# We can create not just a matrix but a multi-dimensional matrix
x = torch.rand(5,3,4)
print(f"rand(5,3,4) tensor: {x}")
# Create an array - this is always there in tensor
# Create 5 arrays
# Add a 3x4 matrix to each array
# 5 arrays of 3x4 matrices
# An array of matrices is 3 dimensional

rand(5,3,4) tensor: tensor([[[0.0069, 0.2173, 0.0387, 0.2910],
         [0.0145, 0.3870, 0.5286, 0.1646],
         [0.6071, 0.9049, 0.1353, 0.9172]],

        [[0.0260, 0.4227, 0.7512, 0.1062],
         [0.6779, 0.5181, 0.2139, 0.2669],
         [0.1269, 0.6317, 0.6647, 0.2940]],

        [[0.7928, 0.7729, 0.1697, 0.9853],
         [0.7895, 0.2844, 0.7627, 0.6139],
         [0.6674, 0.4255, 0.4650, 0.7667]],

        [[0.3561, 0.6931, 0.4975, 0.6122],
         [0.7154, 0.3646, 0.5828, 0.2671],
         [0.1304, 0.7480, 0.6283, 0.7615]],

        [[0.0031, 0.9614, 0.6738, 0.7885],
         [0.2216, 0.6322, 0.3737, 0.4033],
         [0.1195, 0.3264, 0.3131, 0.4307]]])


In [19]:
# We can create not just a matrix but a multi-dimensional matrix
x = torch.rand(5,3,4,2)
print(f"rand(5,3,4,2) tensor: {x}")
# Create an array - this is always there in tensor
# Create 5 arrays
# Add 3 arrays to each of them which are of the size 4x2 matrices

rand(5,3,4,2) tensor: tensor([[[[0.3867, 0.7871],
          [0.4994, 0.7628],
          [0.0709, 0.5045],
          [0.1045, 0.5737]],

         [[0.8935, 0.6909],
          [0.8444, 0.8167],
          [0.9769, 0.7616],
          [0.5206, 0.4036]],

         [[0.9832, 0.8988],
          [0.8030, 0.0961],
          [0.6089, 0.1948],
          [0.8619, 0.5329]]],


        [[[0.4174, 0.3828],
          [0.6711, 0.5991],
          [0.4497, 0.2077],
          [0.7083, 0.8774]],

         [[0.7107, 0.5959],
          [0.1259, 0.7558],
          [0.5013, 0.7834],
          [0.1566, 0.7683]],

         [[0.0089, 0.7492],
          [0.6587, 0.8280],
          [0.6375, 0.6720],
          [0.1129, 0.2710]]],


        [[[0.5348, 0.5698],
          [0.5840, 0.6146],
          [0.7278, 0.1257],
          [0.3793, 0.6112]],

         [[0.9838, 0.1248],
          [0.1352, 0.4494],
          [0.2285, 0.0960],
          [0.6626, 0.8856]],

         [[0.1454, 0.7928],
          [0.9031, 0.9230],
      

In [20]:
# Get size of a tensor
# 1. calling function - size()
# 2. attribute - shape

In [21]:
print(f"x.size() = {x.size()}")
print(f"x.shape = {x.shape}")

x.size() = torch.Size([5, 3, 4, 2])
x.shape = torch.Size([5, 3, 4, 2])


In [22]:
print(f"x.size(0) = {x.size(0)}")
print(f"x.shape[0] = {x.shape[0]}")

x.size(0) = 5
x.shape[0] = 5


In [23]:
# Datatypes
# By default the datatype is float32
# But we can specify while creating an array

In [24]:
print(x.dtype)

torch.float32


In [25]:
x = torch.zeros(4,2, dtype=torch.float16)
print(x.dtype)
print(x.shape)
print(x)

torch.float16
torch.Size([4, 2])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float16)


In [26]:
# Construct tensor from data
x = torch.tensor(
    [
        [1,2]
    ]
)
print(x.dtype)
print(x.shape)
print(x)

torch.int64
torch.Size([1, 2])
tensor([[1, 2]])


In [27]:
# Construct tensor from data
x = torch.tensor(
    [
      [1,2],
      [2,3],
      [2,3]
    ]
)
print(x.dtype)
print(x.shape)
print(x)

torch.int64
torch.Size([3, 2])
tensor([[1, 2],
        [2, 3],
        [2, 3]])


In [28]:
# Construct tensor from data
x = torch.tensor(
    [
        [
          [1,2],
          [2,3],
          [2,3]
        ]
    ]
)
print(x.dtype)
print(x.shape)
print(x)

torch.int64
torch.Size([1, 3, 2])
tensor([[[1, 2],
         [2, 3],
         [2, 3]]])


In [29]:
# Construct tensor from data
x = torch.tensor(
    [
        [
          [1,2],
          [2,3],
          [2,3]
        ],
        [
          [1,2],
          [2,3],
          [2,3]
        ]
    ]
)
print(x.dtype)
print(x.shape)
print(x)

torch.int64
torch.Size([2, 3, 2])
tensor([[[1, 2],
         [2, 3],
         [2, 3]],

        [[1, 2],
         [2, 3],
         [2, 3]]])


In [30]:
# Construct tensor from data
x = torch.tensor(
    [
        [
          [1.5,2],
          [2,3],
          [2,3]
        ],
        [
          [1,2],
          [2,3],
          [2,3]
        ]
    ]
)
print(x.dtype)
print(x.shape)
print(x)

torch.float32
torch.Size([2, 3, 2])
tensor([[[1.5000, 2.0000],
         [2.0000, 3.0000],
         [2.0000, 3.0000]],

        [[1.0000, 2.0000],
         [2.0000, 3.0000],
         [2.0000, 3.0000]]])


In [31]:
# If autograd should record operations on the returned tensor
# Calculate gradient for this tensor
# This is a variablel in your model that you want to optimize
x = torch.tensor(
    [
        [
          [1.5,2],
          [2,3],
          [2,3]
        ],
        [
          [1,2],
          [2,3],
          [2,3]
        ]
    ], requires_grad=True,
)
print(x.dtype)
print(x.shape)
print(x)

torch.float32
torch.Size([2, 3, 2])
tensor([[[1.5000, 2.0000],
         [2.0000, 3.0000],
         [2.0000, 3.0000]],

        [[1.0000, 2.0000],
         [2.0000, 3.0000],
         [2.0000, 3.0000]]], requires_grad=True)


In [32]:
# Mathematical operations on tensors
x = torch.ones([1,2])
y = torch.ones([1,2])
print(x + y)
print(torch.add(x,y))
print(x.add_(y))

tensor([[2., 2.]])
tensor([[2., 2.]])
tensor([[2., 2.]])


In [33]:
# Subtraction
x = torch.rand([1,2])
y = torch.rand([1,2])
print(x, y)
print(x-y)
print(x.subtract(y))
print(x.sub_(y))

tensor([[0.8261, 0.4632]]) tensor([[0.0942, 0.8806]])
tensor([[ 0.7319, -0.4175]])
tensor([[ 0.7319, -0.4175]])
tensor([[ 0.7319, -0.4175]])


In [34]:
print(x, y)

tensor([[ 0.7319, -0.4175]]) tensor([[0.0942, 0.8806]])


In [35]:
# Multiplication
x = torch.ones([1,2])
y = torch.rand([1,2])
print(x, y)
print(x*y)
print(x.mul(y))
print(x.mul_(y))
print(x, y)

tensor([[1., 1.]]) tensor([[0.7701, 0.7147]])
tensor([[0.7701, 0.7147]])
tensor([[0.7701, 0.7147]])
tensor([[0.7701, 0.7147]])
tensor([[0.7701, 0.7147]]) tensor([[0.7701, 0.7147]])


In [36]:
# Division
x = torch.ones([1,2])
y = torch.rand([1,2])
print(x, y)
print(x/y)
print(x.div(y))
print(x.div_(y))
print(x, y)

tensor([[1., 1.]]) tensor([[0.4003, 0.9854]])
tensor([[2.4983, 1.0148]])
tensor([[2.4983, 1.0148]])
tensor([[2.4983, 1.0148]])
tensor([[2.4983, 1.0148]]) tensor([[0.4003, 0.9854]])


In [37]:
# Slicing
x = torch.rand(5,3)
print(x.shape)
print(x)
y = x[:,0] # All rows, 0th column
print(y, y.shape)
z = x[1,:] # First row, all columns
print(z, z.shape)
w = x[0,2] # Get element at 0,2
print(w, w.shape)


torch.Size([5, 3])
tensor([[0.9066, 0.9289, 0.7303],
        [0.4865, 0.8134, 0.1502],
        [0.5437, 0.4289, 0.1288],
        [0.6482, 0.2955, 0.9913],
        [0.9147, 0.1128, 0.6882]])
tensor([0.9066, 0.4865, 0.5437, 0.6482, 0.9147]) torch.Size([5])
tensor([0.4865, 0.8134, 0.1502]) torch.Size([3])
tensor(0.7303) torch.Size([])


In [38]:
# Slicing
x = torch.rand([5,3])
print(x.shape)
print(x)
y = x[:,0] # All rows, 0th column
print(y, y.shape)
z = x[1,:] # First row, all columns
print(z, z.shape)
w = x[0,2] # Get element at 0,2
print(w, w.shape)


torch.Size([5, 3])
tensor([[0.1031, 0.2383, 0.2272],
        [0.1137, 0.5820, 0.3089],
        [0.7386, 0.9877, 0.3242],
        [0.5483, 0.7725, 0.6312],
        [0.6583, 0.4254, 0.7626]])
tensor([0.1031, 0.1137, 0.7386, 0.5483, 0.6583]) torch.Size([5])
tensor([0.1137, 0.5820, 0.3089]) torch.Size([3])
tensor(0.2272) torch.Size([])


In [39]:
w.item()

0.22715061902999878

In [40]:
w

tensor(0.2272)

In [41]:
# w.item() gives the actual float value

In [43]:
# Reshape a tensor with view
print(x)
print(x.shape)
y = x.view(15)
print(y)
print(y.shape)

tensor([[0.1031, 0.2383, 0.2272],
        [0.1137, 0.5820, 0.3089],
        [0.7386, 0.9877, 0.3242],
        [0.5483, 0.7725, 0.6312],
        [0.6583, 0.4254, 0.7626]])
torch.Size([5, 3])
tensor([0.1031, 0.2383, 0.2272, 0.1137, 0.5820, 0.3089, 0.7386, 0.9877, 0.3242,
        0.5483, 0.7725, 0.6312, 0.6583, 0.4254, 0.7626])
torch.Size([15])


In [45]:
x = torch.rand(5,3,4)
print(x)
print(x.shape)
y = x.view(60)
print(y)
print(y.shape)

tensor([[[0.4839, 0.5503, 0.1367, 0.7738],
         [0.7449, 0.9215, 0.6750, 0.5702],
         [0.1673, 0.7236, 0.5535, 0.2592]],

        [[0.7251, 0.1456, 0.7903, 0.0257],
         [0.1532, 0.5184, 0.9723, 0.6469],
         [0.7261, 0.9799, 0.0569, 0.0188]],

        [[0.6133, 0.5427, 0.4241, 0.7047],
         [0.9976, 0.3282, 0.6003, 0.0628],
         [0.9176, 0.1213, 0.4607, 0.7075]],

        [[0.0568, 0.1189, 0.4918, 0.4531],
         [0.4764, 0.8959, 0.6101, 0.4889],
         [0.5100, 0.7227, 0.3036, 0.0679]],

        [[0.2725, 0.6473, 0.5475, 0.7552],
         [0.3905, 0.4206, 0.0426, 0.0491],
         [0.7784, 0.9616, 0.2805, 0.2708]]])
torch.Size([5, 3, 4])
tensor([0.4839, 0.5503, 0.1367, 0.7738, 0.7449, 0.9215, 0.6750, 0.5702, 0.1673,
        0.7236, 0.5535, 0.2592, 0.7251, 0.1456, 0.7903, 0.0257, 0.1532, 0.5184,
        0.9723, 0.6469, 0.7261, 0.9799, 0.0569, 0.0188, 0.6133, 0.5427, 0.4241,
        0.7047, 0.9976, 0.3282, 0.6003, 0.0628, 0.9176, 0.1213, 0.4607, 0.7075,
   

In [49]:
z = x.view(-1,5) # -1 infers the dimension based on other value
print(z)
print(z.shape)

tensor([[0.4839, 0.5503, 0.1367, 0.7738, 0.7449],
        [0.9215, 0.6750, 0.5702, 0.1673, 0.7236],
        [0.5535, 0.2592, 0.7251, 0.1456, 0.7903],
        [0.0257, 0.1532, 0.5184, 0.9723, 0.6469],
        [0.7261, 0.9799, 0.0569, 0.0188, 0.6133],
        [0.5427, 0.4241, 0.7047, 0.9976, 0.3282],
        [0.6003, 0.0628, 0.9176, 0.1213, 0.4607],
        [0.7075, 0.0568, 0.1189, 0.4918, 0.4531],
        [0.4764, 0.8959, 0.6101, 0.4889, 0.5100],
        [0.7227, 0.3036, 0.0679, 0.2725, 0.6473],
        [0.5475, 0.7552, 0.3905, 0.4206, 0.0426],
        [0.0491, 0.7784, 0.9616, 0.2805, 0.2708]])
torch.Size([12, 5])


In [51]:
z = x.view(2,30)
print(z)
print(z.shape)

tensor([[0.4839, 0.5503, 0.1367, 0.7738, 0.7449, 0.9215, 0.6750, 0.5702, 0.1673,
         0.7236, 0.5535, 0.2592, 0.7251, 0.1456, 0.7903, 0.0257, 0.1532, 0.5184,
         0.9723, 0.6469, 0.7261, 0.9799, 0.0569, 0.0188, 0.6133, 0.5427, 0.4241,
         0.7047, 0.9976, 0.3282],
        [0.6003, 0.0628, 0.9176, 0.1213, 0.4607, 0.7075, 0.0568, 0.1189, 0.4918,
         0.4531, 0.4764, 0.8959, 0.6101, 0.4889, 0.5100, 0.7227, 0.3036, 0.0679,
         0.2725, 0.6473, 0.5475, 0.7552, 0.3905, 0.4206, 0.0426, 0.0491, 0.7784,
         0.9616, 0.2805, 0.2708]])
torch.Size([2, 30])


In [52]:
z = x.view(6,-1)
print(z)
print(z.shape)

tensor([[0.4839, 0.5503, 0.1367, 0.7738, 0.7449, 0.9215, 0.6750, 0.5702, 0.1673,
         0.7236],
        [0.5535, 0.2592, 0.7251, 0.1456, 0.7903, 0.0257, 0.1532, 0.5184, 0.9723,
         0.6469],
        [0.7261, 0.9799, 0.0569, 0.0188, 0.6133, 0.5427, 0.4241, 0.7047, 0.9976,
         0.3282],
        [0.6003, 0.0628, 0.9176, 0.1213, 0.4607, 0.7075, 0.0568, 0.1189, 0.4918,
         0.4531],
        [0.4764, 0.8959, 0.6101, 0.4889, 0.5100, 0.7227, 0.3036, 0.0679, 0.2725,
         0.6473],
        [0.5475, 0.7552, 0.3905, 0.4206, 0.0426, 0.0491, 0.7784, 0.9616, 0.2805,
         0.2708]])
torch.Size([6, 10])


In [53]:
# Converting a pytorch tensor into numpy array and vice versa

In [54]:
# When the tensor is stored in CPU and not in GPU, then the converted numpy
# array also gets modified as the original tensor

In [56]:
b = x.numpy()
print(type(x))
print(type(b))
print(b)
print(b.shape)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
[[[0.4838676  0.5503141  0.13674271 0.7738293 ]
  [0.74489135 0.9215167  0.6749532  0.5701689 ]
  [0.16729409 0.7236181  0.5535234  0.25916177]]

 [[0.72508043 0.14561272 0.7903318  0.02572232]
  [0.15321434 0.5183995  0.9722826  0.64686364]
  [0.72611564 0.9799357  0.05692846 0.01883441]]

 [[0.6132724  0.5426925  0.4241264  0.7046928 ]
  [0.9975533  0.3282073  0.6002666  0.06278932]
  [0.91756314 0.12127942 0.46074593 0.70754164]]

 [[0.05682254 0.11889791 0.49177152 0.45309561]
  [0.4764201  0.895891   0.6100536  0.48892444]
  [0.5099641  0.7227339  0.30356956 0.06793278]]

 [[0.2725411  0.64725804 0.5474964  0.7552064 ]
  [0.3905337  0.4206013  0.04262048 0.04910046]
  [0.7783745  0.9616435  0.2805012  0.27078986]]]
(5, 3, 4)


In [57]:
x+=1
print(x)
print(b)

tensor([[[1.4839, 1.5503, 1.1367, 1.7738],
         [1.7449, 1.9215, 1.6750, 1.5702],
         [1.1673, 1.7236, 1.5535, 1.2592]],

        [[1.7251, 1.1456, 1.7903, 1.0257],
         [1.1532, 1.5184, 1.9723, 1.6469],
         [1.7261, 1.9799, 1.0569, 1.0188]],

        [[1.6133, 1.5427, 1.4241, 1.7047],
         [1.9976, 1.3282, 1.6003, 1.0628],
         [1.9176, 1.1213, 1.4607, 1.7075]],

        [[1.0568, 1.1189, 1.4918, 1.4531],
         [1.4764, 1.8959, 1.6101, 1.4889],
         [1.5100, 1.7227, 1.3036, 1.0679]],

        [[1.2725, 1.6473, 1.5475, 1.7552],
         [1.3905, 1.4206, 1.0426, 1.0491],
         [1.7784, 1.9616, 1.2805, 1.2708]]])
[[[1.4838676 1.5503142 1.1367427 1.7738292]
  [1.7448914 1.9215167 1.6749532 1.570169 ]
  [1.167294  1.723618  1.5535234 1.2591617]]

 [[1.7250805 1.1456127 1.7903318 1.0257223]
  [1.1532143 1.5183995 1.9722826 1.6468637]
  [1.7261157 1.9799356 1.0569284 1.0188344]]

 [[1.6132724 1.5426924 1.4241264 1.7046928]
  [1.9975533 1.3282073 1.6002666 

In [58]:
# From numpy to torch tensor


In [61]:
import numpy as np
a = np.ones(5)
print(a, type(a))
b = torch.from_numpy(a) # Will share the same memory
print(b, type(b))
c = torch.tensor(a) # This creates a copy
print(c, type(c))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [62]:
a += 1
print(a)
print(b)
print(c)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [63]:
# GPU support

In [64]:
# By default, all the tensors are created on CPU
# We can move them to GPU or create them on GPU

In [5]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)
print(device)

cuda


In [3]:
# If you have multiple GPUs, use -
device = torch.device(
    "cuda:1" if torch.cuda.is_available() else "cpu"
)
print(device)

cuda:1


In [6]:
x = torch.rand(5,3).to(device) # Move tensor to GPU device, change datatype also
print(x)

tensor([[0.8157, 0.7263, 0.3955],
        [0.7447, 0.0404, 0.2577],
        [0.3143, 0.6134, 0.5622],
        [0.9786, 0.2026, 0.5365],
        [0.5820, 0.3412, 0.5626]], device='cuda:0')


In [7]:
print(type(x))

<class 'torch.Tensor'>


In [8]:
print(x.dtype)

torch.float32


In [9]:
x = x.to("cuda")
print(x)

tensor([[0.8157, 0.7263, 0.3955],
        [0.7447, 0.0404, 0.2577],
        [0.3143, 0.6134, 0.5622],
        [0.9786, 0.2026, 0.5365],
        [0.5820, 0.3412, 0.5626]], device='cuda:0')


In [10]:
y = x.to("cpu")
print(y)

tensor([[0.8157, 0.7263, 0.3955],
        [0.7447, 0.0404, 0.2577],
        [0.3143, 0.6134, 0.5622],
        [0.9786, 0.2026, 0.5365],
        [0.5820, 0.3412, 0.5626]])


In [11]:
z = torch.rand(5,3, device=device)
print(z)

tensor([[0.7581, 0.2643, 0.8428],
        [0.9616, 0.7309, 0.2646],
        [0.8503, 0.2619, 0.3669],
        [0.0749, 0.9984, 0.5912],
        [0.5797, 0.2426, 0.5284]], device='cuda:0')
