<a href="https://colab.research.google.com/github/Adhira-Deogade/pytorch-learnings/blob/main/pytroch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# Tutorial - https://www.youtube.com/watch?v=OIenNRt2bjg


In [30]:
# Pytorch autograd package provides automatic differentiation
# for all operations on tensors
# torch.autograd is an engine which provides/computes - partial differentiation
# applying the chain rule

In [31]:
import torch

In [32]:
x = torch.rand(5,3, requires_grad=True)
print(x)

tensor([[0.4465, 0.1666, 0.9183],
        [0.7610, 0.1475, 0.7931],
        [0.9348, 0.2689, 0.1953],
        [0.0866, 0.1485, 0.2502],
        [0.2408, 0.3203, 0.8141]], requires_grad=True)


In [33]:
y = x + 2
print(y)

tensor([[2.4465, 2.1666, 2.9183],
        [2.7610, 2.1475, 2.7931],
        [2.9348, 2.2689, 2.1953],
        [2.0866, 2.1485, 2.2502],
        [2.2408, 2.3203, 2.8141]], grad_fn=<AddBackward0>)


In [34]:
print(x-y)

tensor([[-2.0000, -2.0000, -2.0000],
        [-2.0000, -2.0000, -2.0000],
        [-2.0000, -2.0000, -2.0000],
        [-2.0000, -2.0000, -2.0000],
        [-2.0000, -2.0000, -2.0000]], grad_fn=<SubBackward0>)


In [35]:
# y was created as a function of some operation, so it has grad_fn attribute
print(y.grad_fn)

In [36]:
print(x.grad_fn)

None


In [37]:
# Do more operations
z = x * y * 6
print(z)
print(z.mean())

tensor([[ 6.5534,  2.1664, 16.0790],
        [12.6068,  1.9008, 13.2918],
        [16.4607,  3.6605,  2.5719],
        [ 1.0840,  1.9140,  3.3774],
        [ 3.2375,  4.4599, 13.7450]], grad_fn=<MulBackward0>)
tensor(6.8739, grad_fn=<MeanBackward0>)


In [38]:
# Let's compute the gradients with backpropagation
# We perform a computation, once it's completed, we can call .backwards()
# This will compute dervation for us

In [39]:
# grad can be implicitly created only for scalar outputs
print(x.grad)
z.mean().backward()
print(x.grad) # dz/dx

None
tensor([[1.1572, 0.9333, 1.5346],
        [1.4088, 0.9180, 1.4345],
        [1.5478, 1.0151, 0.9562],
        [0.8693, 0.9188, 1.0001],
        [0.9926, 1.0563, 1.4513]])


In [40]:
# All the operations will be tracked, when we set requires_grad=True
# We are going through a forward pass in our network

In [41]:
# After the forward pass, in the end we calculate the loss, mean squared error
# Then we apply backpropagation on loss, which computes derivative
# of loss with respect to weights

In [42]:
# After each iteration, we need to empty the gradient with optimizer.zero_grad()

In [43]:
# Stop a tensor from tracking history


In [44]:
a = torch.rand(5,3)
print(a)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)

tensor([[0.0710, 0.5669, 0.6203],
        [0.7935, 0.5192, 0.1727],
        [0.7005, 0.8667, 0.1141],
        [0.8142, 0.3578, 0.4481],
        [0.9932, 0.9603, 0.1531]])
False
None


In [58]:
a = torch.rand(5,3, requires_grad=True)
print(a)
b = (a * a).sum()
print(a.requires_grad)
print(b.grad_fn)
print(b.grad)

tensor([[0.7261, 0.2417, 0.3508],
        [0.6065, 0.8258, 0.4881],
        [0.7506, 0.8127, 0.3523],
        [0.4364, 0.3862, 0.8449],
        [0.7650, 0.9637, 0.3953]], requires_grad=True)
True
None


<ipython-input-58-0f4f7934cfdd>:6: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(b.grad)


In [48]:
a = torch.rand(5,3, requires_grad=True)
print(a)
b = a.detach() # This will create a copy
print(a.requires_grad)
print(b.requires_grad)

tensor([[0.9547, 0.9584, 0.9174],
        [0.2494, 0.1716, 0.7701],
        [0.2305, 0.1429, 0.2807],
        [0.4873, 0.7333, 0.6997],
        [0.6523, 0.6197, 0.0164]], requires_grad=True)
True
False


In [49]:
a = torch.rand(5,3, requires_grad=True)
print(a)
with torch.no_grad():
    b = a * 2
    print(b)
print(a.requires_grad)
print(b.requires_grad)

tensor([[0.8324, 0.6352, 0.6020],
        [0.6695, 0.2769, 0.2895],
        [0.9454, 0.1995, 0.4333],
        [0.6964, 0.7989, 0.6934],
        [0.1505, 0.1801, 0.8001]], requires_grad=True)
tensor([[1.6649, 1.2703, 1.2040],
        [1.3391, 0.5537, 0.5790],
        [1.8909, 0.3991, 0.8666],
        [1.3927, 1.5978, 1.3867],
        [0.3010, 0.3603, 1.6001]])
True
False


In [50]:
# The above step is required when we are in evaluation stage

In [52]:
# Gradient Descent Autograd
# Linear regression example:
# f(x) = w*x + b
# Here: f(x) = 2x

In [56]:
print(b.grad)

None


In [57]:
print(a.grad)

None
